version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Navigate to project directory and build
          command: cd TP1 && mvn -B -DskipTests clean package

      - run:
          name: Run Unit tests
          command: cd TP1 && mvn clean test jacoco:report

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Build and run Checkstyle
          command: mvn checkstyle:checkstyle
        
      - run:  
          name: Upload Checkstyle report
          uses: actions/upload-artifact@v3
          with:
            name: checkstyle-report
            path: target/checkstyle/checkstyle.html

workflows:
  version: 2
  sample-workflow:
    when:
      branch: master
    jobs:
      - build-and-test
