version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Build the project
          command: |
            cd TP1
            mvn -B -DskipTests clean package

      - run:
          name: Run Unit Tests and Generate Coverage Report
          command: |
            cd TP1
            mvn clean test jacoco:report

      - codecov/upload:
          file: ./TP1/target/site/jacoco/jacoco.xml

      - run:
          name: Run Checkstyle
          command: |
            cd TP1
            mvn checkstyle:checkstyle

      - store_artifacts:
          path: TP1/target/site/checkstyle.html
          destination: checkstyle-report

workflows:
  version: 2
  build-and-check:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
