version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Build the project
          command: |
            cd TP1
            mvn -B -DskipTests clean package

      - run:
          name: Run Unit Tests and Generate Coverage Report
          command: |
            cd TP1
            mvn clean test jacoco:report

      - codecov/upload:
          file: ./TP1/target/site/jacoco/jacoco.xml

      - store_artifacts:
          path: TP1/target/site/jacoco
          destination: jacoco-report

      - run:
          name: Generate Javadoc
          command: |
            cd TP1
            mvn javadoc:javadoc

      - store_artifacts:
          path: TP1/target/site/apidocs
          destination: javadoc

      - persist_to_workspace:
          root: .
          paths:
            - TP1/target/site/apidocs

  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Run Checkstyle
          command: |
            cd TP1
            mvn checkstyle:checkstyle

      - store_artifacts:
          path: TP1/target/site/checkstyle.html
          destination: checkstyle-report

  deploy-javadoc:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: Install gh-pages tool
          command: |
            sudo apt update
            sudo apt install -y git
            npm install -g gh-pages
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            cd /TP1/target/site/apidocs
            git init
            git config user.name "CircleCI"
            git config user.email "wendy.toledo.99@gmail.com"
            gh-pages -d .

workflows:
  version: 2
  build-and-check:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - checkstyle:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-javadoc:
          requires:
            - build-and-test
            - checkstyle
          filters:
            branches:
              only: master
