version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:20.0
      
    steps:
      - checkout

      - run:
          name: Navigate to project directory
          command: cd TP1 && mvn -B -DskipTests clean package
          
      - run:
          name: Unit tests with Jacoco
          command: cd TP1 && mvn test jacoco:report

      - run:
          name: Checkstyle Analysis
          command: cd TP1 && mvn checkstyle:checkstyle
      
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
          
  javadoc:
    docker:
      - image: cimg/openjdk:20.0
    steps:
      - checkout
      
      - run:
          name: Set GIT_SSH_COMMAND to use the right SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
      - run:
          name: Generate Javadoc
          command: |
            cd TP1 && mvn javadoc:javadoc

      - add_ssh_keys:
          fingerprints:
            - "SHA256:ISaAG2OVZ+UN3OW6BXaM4Jo5aq9HzWrrk5klO1M6hWA"   
      - run:
          name: Install and config gh-pages
          command: |
            git config --global user.email "ci-build@WendyToledo.com"
            git config --global user.name "ci-build"

            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages
            cd gh-pages && git checkout -b gh-pages        
            cp -r TP1/target/site/apidocs/* ./
            
            git add -A
            git commit -m "[skip ci] Updated Javadoc"
            git push origin gh-pages --force 

workflows:
  version: 2
  sample-workflow: 
    when:
      branch: master
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - javadoc:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
