version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:20.0
      
    steps:
      - checkout

      - run:
          name: Navigate to project directory
          command: cd TP1 && mvn -B -DskipTests clean package
          
      - run:
          name: Unit tests with Jacoco
          command: cd TP1 && mvn test jacoco:report

      - run:
          name: Checkstyle Analysis
          command: cd TP1 && mvn checkstyle:checkstyle
      
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
          
  javadoc:
    docker:
      - image: cimg/openjdk:20.0
    steps:
      - checkout
          
      - run:
          name: Generate Javadoc
          command: cd TP1 && mvn javadoc:javadoc

      - run:
          name: Publish
          command: |
            cd TP1
            git config --global user.email "ci-build@WendyToledo.com"
            git config --global user.name "ci-build"
            git iniy
            git remote remove origin || true
            git remote add origin https://$GH_TOKEN@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
            git fetch origin || true
            git checkout -b gh-pages
            mkdir -p docs
            cp -r target/site/apidocs/* docs/
            git add .
            git commit -m "Publish Javadoc"
            git push --force origin gh-pages

workflows:
  version: 2
  sample-workflow: 
    when:
      branch: master
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - javadoc:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
