version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Navigate to project directory and build
          command: cd TP1 && mvn -B -DskipTests clean package

      - run:
          name: Run Unit Tests with Jacoco and generate coverage report
          command: cd TP1 && mvn clean test/java/fr/univavignon/pokedex/api jacoco:report

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  sample-workflow:
    when:
      branch: master
    jobs:
      - build-and-test
