version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Build the project
          command: cd TP1 && mvn -B -DskipTests clean package

      - run:
          name: Run Unit Tests and Generate Coverage Report
          command: cd TP1 && mvn clean test jacoco:report
          
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  checkstyle:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      
      - run:
          name: Run Checkstyle
          command: cd TP1 && mvn checkstyle:checkstyle
            
  generate-javadoc:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: cd TP1 && mvn javadoc:javadoc
            
      - add_ssh_keys:
          fingerprints:
            - "SHA256:HMDNPYGkfbBQ4kJVkCGeZrnLFSAujMuIfwWS8E+THSk"

      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            git config user.email "ci-build@twendy.net"
            git config user.name "ci-build"
            
            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages
            cd gh-pages && git checkout -b gh-pages 
            cp -r TP1/target/site/apidocs/* ./
            
            git add -A
            git commit -m "[skip ci] Updated Javadoc"
            git push origin gh-pages --force
            

workflows:
  version: 2
  build-and-check:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - checkstyle:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - generate-javadoc:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
