version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      - run:
          name: Navigate to project directory and build
          command: cd TP1 && mvn -B -DskipTests clean package

      - run:
          name: Run Unit tests and Generate Coverage
          command: cd TP1 && mvn clean test jacoco:report

      - codecov/upload:
          name: Upload coverage to Codecov
          file: ./TP1/target/site/jacoco/jacoco.xml

      - run:
          name: Build and Run Checkstyle
          command: cd TP1 && mvn checkstyle:checkstyle

      - persist_to_workspace:
          root: TP1
          paths:
            - target/site

workflows:
  version: 2
  build-and-check:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
